services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8020:80"
    env_file:
      - .env
    depends_on:
      - db
      - memcached
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always
    ports:
      - "11211:11211"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8087:80"
    environment:
      PMA_HOST: db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
